### ISSUE TITLE
Build Menu categories can get overfilled

### ISSUE THREAD

**Issue by PataNautic** [GalaxyRoblox/Issues-Public#72] opened 2024-07-20 09:18 UTC
In certain cases, especially on LBM ( https://discord.com/channels/204965774618656769/1263956949091881120/1263956949091881120), the ScrollingFrame is not able to fit all of the available ships in a category if there are too many options. This causes the player to be unable to build certain ships they should have access to.

I believe this is as simple as making it so the ScrollingFrame size is dependent on the amount of ships per category, but this may be more complicated than I realize

**Comment by Wingysam** [comment] 2024-07-20 10:22
Dupe of #14

(haha now we've both made a dupe of each other's issue)

**Closed as not planned** 2024-07-20 10:23 UTC
Labels: duplicate
