### ISSUE TITLE
Ships sometimes randomly despawn when their health hits 0, instead of dying

### ISSUE THREAD

**Issue by cswimr** [GalaxyRoblox/Issues-Public#69] opened 2024-07-16 04:40 UTC
Link to video from reporting user: https://youtu.be/ZAEoe28LII0
F9 logs (I don't think these are particularly relevant but they were provided):  
![image](https://github.com/user-attachments/assets/48069495-41b9-4e01-a6ea-567516a9c695)

I haven't been able to reproduce this personally, but it has happened before if my memory is correct.

**Comment by PataNautic** [comment] 2024-07-21 21:37
@SeaswimmerTheFsh This appears to be uniquely an issue with the Theseus-X from testing. Since there is a reproducible method, I will close this issue and refer people to GalaxyRoblox/Issues-Staff#68

**Closed as not planned** 2024-07-21 21:41 UTC
Labels: duplicate
